### ISSUE TITLE
Prenova predloge

### ISSUE THREAD

**Issue by katjabercic** [ul-fmf/fmfdelo#6]
Povzeto po @matijapretnar :

- [x] ugotovi, kaj rabiš za PDF/A,
- [ ] preizkusi na starejših in novejših distribucijah,
- [ ] magistrsko delo preklopi na `fmfdelo`,
- [ ] `update.sh`, zipe in podobno prestavi v GitHub actions,
- [ ] združi README.mdje in dodaj FAQ (BOM, drugi paketi?, ...),
- [ ] v README.md in v template dodaj opozorilo, da smo natančno preučili vse možnosti in da igranje s PDF/A paketi ne bo rešilo ničesar,
- [ ] predlagaj VS Code namesto TeXStudia,
- [x] ugotovi, kaj narediti z ukazom `\C`, ki ga predloga prepiše, v osnovi pa je nek neuporaben naglas, ki ga doda `hypertex`. Ali v predlogi sploh rabimo `\R`, `\C` in podobno? Če že mora biti, `\renewcommand` z obrazložitvijo,
- [x] ali se da `\zgenerirajMetaPodatke` avtomatično poklicati na koncu preambule, oz. pred `begin{document}`.
- [ ] dodaj razlago, kako se v BibTeXu pravilno piše naslove, v katerih želimo ohraniti velike začetnice (glej #2 in #3)
- [ ] predlagaj pameten paket za označevanje TODOjev (en predlog, ki sem ga slišal, je bil paket `soul` v kombinaciji s paketom `color`)
- [ ] opozori na morebitne rastrske fonte (#9)

**Comment by katjabercic** [comment]
* (Why can't I use `hyperref` and `\C` together)[https://tex.stackexchange.com/questions/533954/why-cant-i-use-hyperref-and-c-together].
* [Prvi osnutek združenega README-ja](https://github.com/katjabercic/fmfdelo/blob/master/README.md), manjkajo posodobitve in uskladitev s predlogami.

**Comment by matijapretnar** [comment]
- [ ] opozori na morebitne rastrske fonte (#9)

**Comment by matijapretnar** [comment]
Tole bom razbil na več manjših issuejev, ki se jih bo dalo reševati ločeno. Predlagam sledeči vrstni red:

- za diplomska dela se uredi PDF/A
- za diplomska dela se posodobi `README.md`
- magistrska dela se poenoti z diplomskimi deli
- uredi se GitHub akcije
